#cloud-config
repo_update: true
repo_upgrade: all

runcmd:
 - yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
 - amazon-linux-extras install -y ansible
