- name: Check if sealed
  shell: vault status -format json
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  register: vault_status
  failed_when: vault_status.rc > 2

- name: Parse output of vault status
  set_fact:
    vault_status_parsed: "{{ vault_status.stdout | from_json }}"

- name: Reading unseal key contents
  command: cat {{item}}
  register: unseal_keys
  with_fileglob: "{{ unseal_keys_dir_output }}/*"
  delegate_to: localhost
  become: no
  when: vault_status.stdout.sealed

- name: Unseal vault with unseal keys
  shell: |
    vault operator unseal {{ item.stdout }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  with_items: "{{unseal_keys.results}}"
  when: vault_status.stdout.sealed
